# Generated by Django 4.1.5 on 2023-04-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Lungs', 'Lungs'), ('Heart', 'Heart'), ('Eyes', 'Eyes'), ('Legs', 'Legs'), ('Ears', 'Ears')], max_length=100)),
                ('image', models.ImageField(upload_to='doctor_image/')),
                ('experience', models.CharField(max_length=100)),
                ('appointment', models.DateTimeField()),
            ],
        ),
    ]
